### ISSUE TITLE
Factions Tag not colored

### ISSUE THREAD

**Issue by GLadithon** [DRE2N/FactionsOne#20] opened 2016-10-30 10:58 UTC
Hey I have just installed this plugin onto my server and I am wondering how I can make it so when people in your faction talk the name is green and when enemy talk it is red etc. Also so when people are in wilderness it dosn't show their tag. My essentials config for chat is   format: '{faction_relcolor}{faction_roleprefix}ยงr{faction_relcolor}{faction_tag_pr}{DISPLAYNAME} {MESSAGE}' Here is my plugin list https://gyazo.com/a0bf9e5b2dd9ece887c53b203f959c68 any help would be appreciated.

**Comment by Sataniel98** [comment] 2016-10-30 16:25
You have to enable colored chat formats in the Factions conf.json. If that doesn't work, the issue is related to the chat plugin.

**Comment by GLadithon** [comment] 2016-10-30 18:05
Can you send me the config with colors enabled

**Comment by GLadithon** [comment] 2016-11-02 20:59
Can you send me the config with colors enabled @Sataniel98

**Comment by Sataniel98** [comment] 2016-11-02 23:30
Seems to be a duplicate of #17.
However, it's "/f config chatParseTagsColored true".

**Comment by GLadithon** [comment] 2016-11-03 21:37
Thanks it worked!

**Closed** 2016-11-03 22:04 UTC
