### ISSUE TITLE
Default User Permissions

### ISSUE THREAD

**Issue by Jakebro2000** [DRE2N/FactionsOne#26] opened 2017-01-25 18:23 UTC
I can't seem to figure out how to let defualt users interact with items in spawn. it is only in spawn where they cannot access anything. no signs, crafting tables, chests, etc... I have gone everywhere else and have gotten no help, so hopefully everybody here can help me. I know that it is a problem with the factions plugin because i made a region with worldguard and enabled interaction, so that isnt the problem, and none of my other plugins could be causing this, since the problem is strictly within the safezone. any help would be greatly appreciated! thanks!

**Comment by Sataniel98** [comment] 2017-01-25 18:28
If it is caused by Factions, then you can change the interaction settings to whatever you need with /f flag and it should be fixed. Note that Minecraft also has a built-in spawn protection that you can disable in the server.properties file.

**Closed** 2017-01-25 18:33 UTC
